//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TreningEntities2 : DbContext
    {
        public TreningEntities2()
            : base("name=TreningEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<AdminMessage> AdminMessage { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<accesstokens> accesstokens { get; set; }
    }
}
