//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Activity { get; set; }
        public string TrainingExperience { get; set; }
        public string Questions { get; set; }
        public string Trainingdays { get; set; }
        public string Goals { get; set; }
    }
}
